### ISSUE TITLE
Erreur dans les créations de cours / stages / bootcamp - Bug - Priorité 2 - VERIFIE

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#12]
Je rentre un workshop qui se tient sur un jour pendant 1h30
Dans duration je mets 1 et j'ai un message d'erreur:
"The duration does not match the format H:i."

Je ne sais pas quel format je dois mettre

<img width="1108" alt="Screenshot 2021-08-06 at 12 40 01" src="https://user-images.githubusercontent.com/212969/128498474-a74e3719-d641-4a58-9c21-75a0571bb9b7.png">
.
VERIFIE

**Comment by sb-fred** [comment]
Quand je sauve avec la duration vide, voici le message d'erreur

Carbon\Exceptions\InvalidFormatException
Could not parse '18/08/2021': DateTime::__construct(): Failed to parse time string (18/08/2021) at position 0 (1): Unexpected character
https://dancefloor.click/courses/30/edit

**Comment by sb-fred** [comment]
Je ne sais pas à quoi sert le bouton View à côté de Save, mais quand je clique dessus, j'ai "404
NOT FOUND"

<img width="1127" alt="Screenshot 2021-08-06 at 12 47 08" src="https://user-images.githubusercontent.com/212969/128499259-6406f70e-2a4d-4e34-9651-9c08f0bf6b22.png">

**Comment by sb-fred** [comment]
J'ai rentré le stage de Laety d'afrobeat sur 1 jour
J'ai l'affichage suivant sans le niveau et sans le jour et l'heure

<img width="1089" alt="Screenshot 2021-08-06 at 12 50 16" src="https://user-images.githubusercontent.com/212969/128499636-fbfb7a4d-0e32-410f-8cc7-538e4ec3ab24.png">

**Comment by sb-fred** [comment]
Le stage est en vert dans la liste, mais je ne le trouve pas en temps qu'élève dans "Courses"
Peut être le format n'est pas adapté.
Je suis allé dans "Workshop", mais la page n'est pas créée.
J'imagine le mieux est de splitter les stages et les cours classiques car les infos ne sont pas du tout les mêmes ?
En attendant, comment puis-je trouver le cours pour m'y inscrire ?

**Comment by sb-fred** [comment]
Peut on mettre en grisé dans le fond de la cellule le format:
dd.mm.yyyy

J'ai fait dd/mm/yyyy et ça a généré une erreur.
Dans tous les cas, je pense qu'il faut traiter l'erreur.

<img width="1119" alt="Screenshot 2021-08-06 at 13 06 49" src="https://user-images.githubusercontent.com/212969/128501570-c142dc92-f8fb-4849-b75d-1c5f809140b5.png">

**Comment by sb-fred** [comment]
Sinon, je dois avoir le même type d'erreur en entrant l'heure je pense, voici le message d'erreur
Voici ce que j'ai rentré pour un stage qui dure 4 jours dans la semaine. Je l'ai mis en bootcamp

<img width="1107" alt="Screenshot 2021-08-06 at 13 08 38" src="https://user-images.githubusercontent.com/212969/128501759-a38b5d0b-efdb-4327-8c29-6a43f69a1768.png">

(mais ce format va nous bloquer si on a un bootcamp qui dure plus d'une semaine)

Voici le message d'erreur

Illuminate\Database\QueryException
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '17.08.2021' for column `dms_click`.`courses`.`start_date` at row 1 (SQL: update `courses` set `start_date` = 17.08.2021, `end_date` = 20.08.2021, `tuesday` = 1, `start_time_tue` = 18:45, `end_time_tue` = 20:00, `wednesday` = 1, `start_time_wed` = 18:45, `end_time_wed` = 20:00, `thursday` = 1, `start_time_thu` = 18:45, `end_time_thu` = 20:00, `friday` = 1, `start_time_fri` = 18:45, `end_time_fri` = 20:00, `courses`.`updated_at` = 2021-08-06 11:09:26 where `id` = 31)
https://dancefloor.click/courses/31/edit

<img width="1250" alt="Screenshot 2021-08-06 at 13 09 56" src="https://user-images.githubusercontent.com/212969/128501883-c4b076ff-3b50-4dc5-b297-65bceecbcc34.png">

**Comment by sb-fred** [comment]
Quand je créé un cours, par défaut il est en open level. 
Si le cours est effectivement en open level, alors je ne touche pas et je sauve, mais le niveau n'est pas enregistré. 
Il faut que je sauve d'abord avec un autre niveau puis que je remette open level et que je sauve pour qu'il s'affiche dans la liste  des cours. 
Il faudrait soit commencer avec un champ vide dans le menu déroulant à la création du cours, ou bien que si je ne touche pas le niveau, il se sauve bien directement avec le niveau par défaut (actuellement: open level)

<img width="789" alt="Screenshot 2021-08-06 at 13 15 24" src="https://user-images.githubusercontent.com/212969/128502447-76a1384e-d2ad-4cde-b491-30bf2b637b23.png">

**Comment by gabzon** [comment]
> Quand je sauve avec la duration vide, voici le message d'erreur
> 
> Carbon\Exceptions\InvalidFormatException
> Could not parse '18/08/2021': DateTime::__construct(): Failed to parse time string (18/08/2021) at position 0 (1): Unexpected character
> https://dancefloor.click/courses/30/edit
> 
> <img alt="Screenshot 2021-08-06 at 12 44 15" width="1223" src="https://user-images.githubusercontent.com/212969/128498939-138e76de-aa04-49e1-bbd6-60a53720c323.png">

Solved

**Comment by gabzon** [comment]
> Quand je créé un cours, par défaut il est en open level.
> Si le cours est effectivement en open level, alors je ne touche pas et je sauve, mais le niveau n'est pas enregistré.
> Il faut que je sauve d'abord avec un autre niveau puis que je remette open level et que je sauve pour qu'il s'affiche dans la liste des cours.
> Il faudrait soit commencer avec un champ vide dans le menu déroulant à la création du cours, ou bien que si je ne touche pas le niveau, il se sauve bien directement avec le niveau par défaut (actuellement: open level)
> 
> <img alt="Screenshot 2021-08-06 at 13 15 24" width="789" src="https://user-images.githubusercontent.com/212969/128502447-76a1384e-d2ad-4cde-b491-30bf2b637b23.png">
