### ISSUE TITLE
Pb droit élève sur les orders/Payment - Priorité 3 - VERIFIE

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#13]
En tant qu'élève je peux ajouter moi même des paiements et modifier des orders.
Je ne devrai pas pouvoir
Cf profil "eugenie P" sur la droite de son dashboard

<img width="1281" alt="Screenshot 2021-08-07 at 00 31 49" src="https://user-images.githubusercontent.com/212969/128577029-86f489b2-4c56-4ba6-a6a0-c0e04a7fba40.png">

J'ai pu cancel mon inscription au cours bien que j'ai déjà payé (Je ne devrai pas pouvoir être autorisé à cancel moi même mon cours après paiement) et je peux encore ajouter des paiements et des Refunds

<img width="954" alt="Screenshot 2021-08-07 at 00 34 41" src="https://user-images.githubusercontent.com/212969/128577199-35e9a62f-3777-49fb-a716-391c6525dccc.png">

**Comment by gabzon** [comment]
only people who have "crud_orders" permissions can cancel or add payments or modify options

**Comment by sb-fred** [comment]
Vérifié !
