### ISSUE TITLE
Pb de suppression de cours par un élève - Priorité 3

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#14]
Connecté en temps qu'élève. Sur mon dashboard d'élève,
J'avais mon cours que j'avais payé. J'avais l'option poubelle sur la droite du cours j'ai cliqué dessus et le cours a disparu.
Ca ne devrait pas être possible. 
Même pour un admin, il ne devrait pas pouvoir supprimer un élève qui a payé d'un cours.

<img width="1266" alt="Screenshot 2021-08-07 at 00 50 29" src="https://user-images.githubusercontent.com/212969/128578048-1656c406-2170-416f-b980-846e9eb161cc.png">

Si je suis mis en standby par l'admin et que je n'ai rien payé, la je devrai pouvoir supprimer le cours en temps qu'élève et c'est possible actuellement

**Comment by gabzon** [comment]
Tu es sur le status était "registered"? car chez moi ca marche

**Comment by gabzon** [comment]
@sb-fred A retester
