### ISSUE TITLE
Récupération des documents étudiants/chomeur - Priorité 1 - VERIFIED

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#16]
L'élève charge son document et sauve (c'était un jpg) ça marche
L'admin veut ensuite regarder le document et il voit juste qu'un document a été uploadé mais ne sait pas ou le récupérer.

La date de fin de validité est également étrange

Ici la vue admin

<img width="736" alt="Screenshot 2021-08-07 at 10 59 51" src="https://user-images.githubusercontent.com/212969/128594960-29d8c01f-0127-4f0f-a3d3-033fe43b9cc9.png">

**Comment by gabzon** [comment]
J'ai debuggé l'erreur de date

Afin de voir le fichier il faut aller sur le detail de la personne et faire click dans view. 

<img width="1525" alt="Screenshot 2021-08-10 at 10 27 47" src="https://user-images.githubusercontent.com/142036/128834520-d173b7db-46b5-42d4-8d71-18094aaedfd2.png">

je ne peux pas afficher l'image car, la personne peut soir uploader une image soir un pdf.

**Comment by sb-fred** [comment]
Du coup, comment ai-je moyen de récupérer le document que l'élève à uploadé ?
Je ne peux pas le télécharger ?
Car le view n'est pas possible sur les pdf j'imagine

**Comment by gabzon** [comment]
tu click sur le bouton view et ca ouvre un nouveau onglet, tu le récupère de la! Click droit download
