### ISSUE TITLE
Pb sauvegarde photo profil - (résolu, cf texte)

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#17]
J'arrive à uploader une photo, mais ensuite le bouton save est grisé et je ne peux pas sauver ma photo de profil.
A noter que j'ai la roue de chargement qui reste sur mon thumbnail de la page

En fait ça marche et c'est très long et ensuite il me dit que je ne peux pas mettre une photo de plus de 1024 Ko.
Je ne sais pas si ce sera beaucoup utilisé en fait...

**Comment by gabzon** [comment]
Ok a discuter afin de voir ce que l'on fait

**Comment by gabzon** [comment]
A faire dans le futur
