### ISSUE TITLE
Bug sur la page de cours - Priorité 3

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#18]
J'ai créé un bootcamp qui dure du mardi ou vendredi.
On s'inscrit en temps qu'élève
Quand on clique sur le cours, on est pre-register (et cela surligne tous les cours de la semaine du bootcamp)

<img width="1275" alt="Screenshot 2021-08-07 at 12 23 24" src="https://user-images.githubusercontent.com/212969/128597055-ff53708a-0098-45d8-8700-7178e654c700.png">

Quand on re-clique sur le cours (car coco ne comprenait pas le chemin), on a un bug

Error
Call to a member function format() on null (View: /home/httpd/vhosts/rapaces.org/dancefloor.click/resources/views/courses/sidebar.blade.php)
https://dancefloor.click/course/33

<img width="1219" alt="Screenshot 2021-08-07 at 12 26 14" src="https://user-images.githubusercontent.com/212969/128597136-0a42e6ed-4a09-4202-b28a-91b17eb7d2ab.png">

**Comment by sb-fred** [comment]
En fait j'ai essayé avec un autre profil, c'est dès qu'on clique sur la vignette du cours et non sur Add to Basket que l'on a le bug

**Comment by gabzon** [comment]
a retester

**Comment by sb-fred** [comment]
Le bug est corrigé, mais j'ai l'apparition intempestive à droite et à gauche du panneau de menu et du cart sur chaque changement de page (Cf vidéo envoyée par whatsapp)
