### ISSUE TITLE
Pop - Up Cart - Compréhension chemin de paiement - priorité 3 - VERIFIED

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#19]
J'ai fait le test avec Coco qui était comme une élève.
Elle s'est inscrite au cours en pre-register et ensuite aucune idée de ou payer.
Elle est allée dans ses mails pour voir si elle avait reçu une confirmation...

1. Ce qui l'aurait aidée c'est qu'il y ait un pop up indiquant que le cours avait bien été ajouté au cart.
Peut être quand le cart n'est pas vide, on pourrait aussi le mettre en gras et le faire changer de couleur.

2. Autre point, après avoir fait le paiement, elle n'avait pas de bouton pour revenir alors elle a fait flèche de retour à gauche et était perdue.

<img width="1275" alt="Screenshot 2021-08-07 at 13 01 25" src="https://user-images.githubusercontent.com/212969/128597976-2a8eee3d-c061-4c73-9b57-8b4e75b17615.png">

On pourrait mettre un bouton - 
**Retour à la page d'accueil**  plutôt que retour au dashboard
après les consignes de paiement
D'ailleurs quand je paie par revolut, j'ai ce bouton de retour, mais pas par virement bancaire

3. Egalement après l'inscription, on arrive directement sur le dashboard, ce serait mieux je pense que l'élève arrive sur la page des cours.

**Comment by gabzon** [comment]
- [ ] Notification lorsqu'on ajoute un cours
- [ ] Button dashboard in bank-transfer
- [ ] Rediriger a la pages des cours plutôt que la page dashboard

**Comment by sb-fred** [comment]
Tout checké et tout marche.
J'aurai peut être juste laissé la notification de l'ajout au cart jusqu'à ce que le client clique dessus pour l'enlever
