### ISSUE TITLE
Problème de balance - Priorité 3

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#20]
On a créé 2 users
Elise et Munire 
Elise a payé 50 CHF d'un cours à 107 CHF donc il lui reste 57 CHF à payer
Munire a payé 107 CHF il ne doit plus rien payer

Sur les 2 comptes on voit qu'il reste 57 CHF à payer et le display n'est pas clair

<img width="1108" alt="Screenshot 2021-08-07 at 12 55 09" src="https://user-images.githubusercontent.com/212969/128597839-e4a97794-e93f-4d38-b01c-f750d15e5786.png">

**Comment by sb-fred** [comment]
Je crée un nouvel utilisateur qui n'a encore souscrit aucun cours et il a aussi cette balance de 57 CHF

<img width="1001" alt="Screenshot 2021-08-07 at 12 58 41" src="https://user-images.githubusercontent.com/212969/128597917-7c245fe5-75dc-49ef-8ebc-114201b1fe0f.png">

**Comment by gabzon** [comment]
problem solved

**Comment by sb-fred** [comment]
VERIFIER
