### ISSUE TITLE
Bug sur la validation d'un paiement

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#21]
Coco a entré les paramètres suivants
Elle a oublié l'ordre associé et message de Bug
Il faudrait un message qui dit qu'il faut rentrer l'ordre associé

Illuminate\Database\QueryException
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `dms_click`.`payments`.`order_id` at row 1 (SQL: insert into `payments` (`code`, `provider`, `method`, `type`, `credit`, `debit`, `currency`, `comments`, `status`, `received_date`, `amount_received`, `mollie_payment_id`, `order_id`, `user_id`, `updated_at`, `created_at`) values (?, ?, revolut, in, 200, ?, ?, ?, paid, 2021-08-03, 200, ?, , 33, 2021-08-07 11:09:40, 2021-08-07 11:09:40))
https://dancefloor.click/payments/create?user=33

<img width="1310" alt="Screenshot 2021-08-07 at 13 09 47" src="https://user-images.githubusercontent.com/212969/128598218-3a2fb5f3-9122-40b1-b382-15b2fb83953b.png">

**Comment by gabzon** [comment]
Order ID field validation required added

**Comment by sb-fred** [comment]
Vérifié
