### ISSUE TITLE
Recalcul de facture pour élève - priorité 2

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#22]
Toujours en testant avec Coco.
On ajoute un cours dans un order pour un élève.
Le recalcul se fait, mais il n'y a plus d'arrondi sur le discount

<img width="724" alt="Screenshot 2021-08-07 at 13 48 12" src="https://user-images.githubusercontent.com/212969/128599097-f5b1d4b5-a9f3-418a-a6e2-46c4f1045576.png">

Coco me demande si c'est possible d'afficher le détail des cours car elle voit la problèmatique des élèves ajoutant des cours en cours de session. Imaginons: un élève prend 2 cours en début de session puis en moitié de session, il ajoute un 3ème cours. A ce moment la, on ne fait pas de discount sur ce 3ème cours (j'avoue je ne le savais pas).
Donc elle elle prend le tarif déjà existant et ajoute par exemple les 4 cours du nouveau cours au tarif existant.

On ne va pas tout changer, mais si elle voit juste le détail des prix comme dans le cart au moment de payer sur cet écran de l'image au dessus de subtotal, ça l'aidera pas mal à recalculer le prix

**Comment by gabzon** [comment]
ok c'est chaud... a Réfléchir

**Comment by gabzon** [comment]
Ajouter le details des cours et prix dans le Show de l'order

**Comment by sb-fred** [comment]
Ca a fonctionné, mais le subtotal se calcul mal (j'ai ouvert un bug à ce sujet). Dans l'EDIT de l'order il se met à jour, mais pas dans l'order
