### ISSUE TITLE
Envoi des mails de confirmation - priorité 3 - A COMPLETER

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#24]
Je ne reçois pas de mail de confirmation quand je m'inscris à des cours et que je suis en processing.
Je devrait recevoir un mail avec les même indications que sur l'écran de confirmation de paiement.
On ajustera le message plus tard

<img width="1005" alt="Screenshot 2021-08-07 at 14 07 03" src="https://user-images.githubusercontent.com/212969/128599603-43427ce9-007b-446c-bef8-d56e759ce829.png">

**Comment by sb-fred** [comment]
Après inscription je reçois ce message

<img width="934" alt="Screenshot 2021-09-01 at 20 21 00" src="https://user-images.githubusercontent.com/212969/131723441-fc607926-6ee1-4577-acb8-79c90110aa2b.png">

le mail automatique marche donc.
Maintenant on va changer le contenu:

"You have successfully registered to the following classes:
**- Classe 1
- Classe 2**

We are now waiting for your payment of  **X CHF** 
Please be aware that you need to pay in order to confirm your place 

Here is the procedure to follow:
**Indications du moyen de paiement**

du style

<img width="993" alt="Screenshot 2021-09-01 at 20 26 21" src="https://user-images.githubusercontent.com/212969/131724069-4eee029e-f88d-418f-b38d-0465d5a87a8c.png">

**Comment by sb-fred** [comment]
Je ferai le français plus tard

**Comment by gabzon** [comment]
J'attends la version française pour faire les changements

**Comment by gabzon** [comment]
pour le details, c'est une amelioration, je vais pas faire encore
