### ISSUE TITLE
Création de fiche de présence - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#25]
Ce n'est pas très simple de créer des fiches à la suite
On doit créer une fiche
Revenir sur View Courses
Recréer une fiche

Ca fait 2 chargements d'écrans.
Il faudrait voir comment un peut améliorer ce process

**Comment by gabzon** [comment]
j'ai ajouté un bouton pour créer une nouvelle attendance

**Comment by sb-fred** [comment]
Yes, it works !
