### ISSUE TITLE
Voir la balance d'un élève - priorité 2

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#26]
En temps qu'admin ou secrétaire, je ne sais pas comment on peut voir la balance d'un élève et en particulier être averti s'il a un crédit que l'on doit déduire de sa nouvelle inscription.
Quel écran dois-je regarder ?

**Comment by gabzon** [comment]
C'était pas prévu pour que ca soit vu par les admins. Surtout avec les messages: your balance is: .....
J'ai développé un code et je l'ai mis dans le users details. 
J'ai garde la meme logique : 

- vert user has credit
- rouge user has debit
- gray balance = 0

ex: http://dancefloor.click/users/5

**Comment by sb-fred** [comment]
Yes, je vois la balance de l'élève en tant qu'admin, c'est très utils pour que je sache si l'élève est à jour. Merci
