### ISSUE TITLE
J'ai rentré le stage de Laety d'afrobeat sur 1 jour

### ISSUE THREAD

**Issue by gabzon** [dancefloor/dms-2#28]
J'ai rentré le stage de Laety d'afrobeat sur 1 jour
J'ai l'affichage suivant sans le niveau et sans le jour et l'heure

<img width="1089" alt="Screenshot 2021-08-06 at 12 50 16" src="https://user-images.githubusercontent.com/212969/128499636-fbfb7a4d-0e32-410f-8cc7-538e4ec3ab24.png">

_Originally posted by @sb-fred in https://github.com/dancefloor/dms-2/issues/12#issuecomment-894176922_

**Comment by gabzon** [comment]
est-ce que cela marche maintenant? 
Je me suis logée sur le df.click et ca marché

**Comment by sb-fred** [comment]
Check OK - je te laisse éditer le titre du bug et ajouter VERIFIED.
