### ISSUE TITLE
Peut on mettre en grisé dans le fond de la cellule le format:

### ISSUE THREAD

**Issue by gabzon** [dancefloor/dms-2#30]
Peut on mettre en grisé dans le fond de la cellule le format:
dd.mm.yyyy

J'ai fait dd/mm/yyyy et ça a généré une erreur.
Dans tous les cas, je pense qu'il faut traiter l'erreur.

<img width="1119" alt="Screenshot 2021-08-06 at 13 06 49" src="https://user-images.githubusercontent.com/212969/128501570-c142dc92-f8fb-4849-b75d-1c5f809140b5.png">

_Originally posted by @sb-fred in https://github.com/dancefloor/dms-2/issues/12#issuecomment-894185748_

**Comment by gabzon** [comment]
J'ai ajouter le date picker, comme ca on force le bon format

**Comment by sb-fred** [comment]
Check OK - je te laisse éditer le titre du bug et ajouter VERIFIED.
