### ISSUE TITLE
Quand je créé un cours, par défaut il est en open level.

### ISSUE THREAD

**Issue by gabzon** [dancefloor/dms-2#32]
Quand je créé un cours, par défaut il est en open level. 
Si le cours est effectivement en open level, alors je ne touche pas et je sauve, mais le niveau n'est pas enregistré. 
Il faut que je sauve d'abord avec un autre niveau puis que je remette open level et que je sauve pour qu'il s'affiche dans la liste  des cours. 
Il faudrait soit commencer avec un champ vide dans le menu déroulant à la création du cours, ou bien que si je ne touche pas le niveau, il se sauve bien directement avec le niveau par défaut (actuellement: open level)

<img width="789" alt="Screenshot 2021-08-06 at 13 15 24" src="https://user-images.githubusercontent.com/212969/128502447-76a1384e-d2ad-4cde-b491-30bf2b637b23.png">

_Originally posted by @sb-fred in https://github.com/dancefloor/dms-2/issues/12#issuecomment-894190171_

**Comment by gabzon** [comment]
Solved!
J'ai mis un champs vide, on doit choisir le niveau

**Comment by sb-fred** [comment]
Check OK - tu peux éditer le titre et ajouter VERIFIED.
