### ISSUE TITLE
Problème de display sur la page de cours - Priorité 2

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#42]
J'ai créé un cours, voici son affichage

<img width="1310" alt="Screenshot 2021-08-30 at 20 09 45" src="https://user-images.githubusercontent.com/212969/131384855-da6ff52f-6d37-41d3-9cc0-2d5ef416d963.png">

**Comment by gabzon** [comment]
si tu regards bien sous le titre popping il y a marque cette address (on voit pas bien car c'est du noir sur du blue foncė): 

https://www.youtube.com/watch?v=eN6JjTSGl-I

Il ne faut pas mettre un url mais plutôt un embed

**Comment by sb-fred** [comment]
OK, en mettant le code embed ca fonctionne bien, mais l'affichage n'est pas top (s'affiche sur la gauche, on s'attend à ce que ce soit centré)

<img width="957" alt="Capture d’écran 2021-09-09 à 17 00 08" src="https://user-images.githubusercontent.com/212969/132710840-7ee1f2af-2567-4db8-b7ff-4e338d62fd51.png">
