### ISSUE TITLE
Création de cours et input de prix - Priorité 1 (moins important=

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#43]
Quand je créé un cours et que je mets un prix, je n'ai même pas le temps de sauver. Dès que je quitte la cellule, j'ai cette affichage

<img width="1041" alt="Screenshot 2021-08-30 at 20 17 23" src="https://user-images.githubusercontent.com/212969/131385623-57266273-eb28-4f92-bb74-5d6a30c6bb96.png">

Le prix n'a pas été enregistré, puisque quand je vais sur le planning, le cours n'a pas de prix.
Il faut que je rerentre dans l'édition du cours à partir du menu avec la liste des cours pour pouvoir remettre un prix

**Comment by gabzon** [comment]
il me faut plus d'info car chez moi ca marche
