### ISSUE TITLE
Un élève en standby se désinscrit - la balance n'est pas actualisée - le cours ne sort pas de l'order - priorité 3 (important)

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#44]
On avait un élève avec un order de 2 cours en "waiting for payment".
J'ai mis un des cours à standby
L'élève a pu se désinscrire
L'élève a bien disparu de la liste des élèves du cours (côté Admin)
Le cours a disparu du dashboard de l'élève

Par contre, le cours apparaît toujours sur l'order de l'élève et la balance n'a pas été mise à jour sur le prix à payer

**Comment by gabzon** [comment]
a discuter car
1) la procedure n'est pas claire. C'est pas toi de mettre quelqu'un en standby, pourquoi le ferai tu?
On doit discuter de cela plus approfondie
