### ISSUE TITLE
Ajout d'un cours à un order - Priorité 0

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#50]
Lorsque j'ajoute un cours à un order, la première fois que je choisis le cours, il s'efface
c'est quand je le choisis une 2ème fois qu'il marche et que je peux l'ajouter.

<img width="1284" alt="Screenshot 2021-08-30 at 22 16 26" src="https://user-images.githubusercontent.com/212969/131399680-e8a86477-06ed-45da-a4ec-027db7983979.png">

**Comment by gabzon** [comment]
Je n'arrive pas a enlever ce bug. Je ne trouves pas le problème et ca prends trop de temps
