### ISSUE TITLE
Parcours utilisateur - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#58]
En tant qu'admin quand j'édite l'order d'un client et que je sauve, je suis renvoyé à la liste globale des orders.
Je devrais revenir sur le profil client avec la liste de ses orders

**Comment by gabzon** [comment]
Malheureusement je ne peux pas, je dois choisir soit la liste des orders soit le profil utilisateur. Cela veut dire que si on va dans la liste des orders et on modifie ca va nous renvoyer dans le profils utilisateur des que je sauve

**Comment by sb-fred** [comment]
Je crois que je préfère être envoyé dans le profil utilisateur car tu vois dans sa liste que ta modification a été prise en compte (Que j'ai modifié l'order depuis son profil ou bien depuis la liste globale).
La liste orders, je peux l'accéder rapidement à tout moment en tant qu'admin en cliquant sur **Orders** 

Egalement, sur le profil utilisateur, peux tu trier les orders dans l'ordre inverse, c'est à dire les plus récentes en haut ? Ce sont celles que l'on regardera en priorité
