### ISSUE TITLE
Courses Admin > Course details > notion de "Confirmed students" - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#64]
Dans la fenetre Course Admin > Course details, il est possible de voir le nb de students en "Confirmed". A partir de quel statut l'Eleve est comptabilisé dans les "confirmed students"? J'imagine à partir du moment ou il est en waiting payment (donc juste le pre-register et standby ne sont pas comptés comme confirmed student)

car il y a un cas où un eleve en "waiting for payment" est comptabilisé en "confirmed" (ca ne devrait pas)
voir Course ID 33 (salsa cubaine initiation)

<img width="981" alt="Capture d’écran 2021-09-01 à 19 25 40" src="https://user-images.githubusercontent.com/212969/131716224-35a23003-c16b-4102-b3fb-6ef96ab47b95.png">

et il y a un cas ou un eleve en "partially registered" n'est PAS comptabilisé en "confirmed" (alors qu'il devrait puisqu'il a déjà payé une partie du cours)
voir Course ID 1 (lady styling cubaine)

<img width="940" alt="Capture d’écran 2021-09-01 à 19 27 43" src="https://user-images.githubusercontent.com/212969/131716518-755de7af-a508-4dc6-8ba1-2f59b5c83ab6.png">

**Comment by gabzon** [comment]
car il y a un cas où un eleve en "waiting for payment" est comptabilisé en "confirmed" (ca ne devrait pas)

On avait parlé une fois pendant longtemps et on avait decidé que du moment ou la personne faire valide une commande, cela deviens un promese et ca bloque ca place. Est-ce que je dois changer ca?

c'est pour pour le partial!
