### ISSUE TITLE
Utilisation de l'icon page + (Add order) depuis le User - Priorité 2

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#68]
en tant qu'admin, quand on clique sur l'icon page + en vue d'ajouter un order à un eleve, on arrive sur une page générique où l'on doit finalement rechercher l'eleve dans toute la liste

<img width="976" alt="Capture d’écran 2021-09-01 à 19 56 06" src="https://user-images.githubusercontent.com/212969/131720193-4c0bbc22-cf0d-4343-8bbe-4c4a31a907e5.png">

on devrait plutôt arriver directement sur la page "edit order" de l'eleve directement, comme suit:

<img width="984" alt="Capture d’écran 2021-09-01 à 19 56 58" src="https://user-images.githubusercontent.com/212969/131720312-a6935175-9247-48b0-af90-ae0b67e0c435.png">

**Comment by gabzon** [comment]
J'ai enlever le bug, par contre j'ai pas fait la premiere parti car c'est une amelioration
