### ISSUE TITLE
Edit Order d'un Eleve, le cours sélectionné saute - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#70]
en tant qu'admin, lorsque je crée un order pour un eleve et que je sélectionne un cours dans la liste déroulante, le cours "saute" tjrs la 1ère fois. je dois aller le sélectionner une 2nde fois dans la liste afin qu'il s'affiche correctement dans le champ "select course".

**Comment by gabzon** [comment]
I cannot find solution yet. I will stop cuz it takes a lot of time
