### ISSUE TITLE
Mauvais sens quand on fait un refund - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#71]
Quand je fais un refund en tant qu'admin, je devrai avoir un debit out plutôt qu'un credit in par défaut

<img width="1382" alt="Screenshot 2021-09-01 at 20 00 41" src="https://user-images.githubusercontent.com/212969/131720776-e781590e-ec86-45ab-b632-2a335fc1049f.png">

et

<img width="1383" alt="Screenshot 2021-09-01 at 20 00 55" src="https://user-images.githubusercontent.com/212969/131720798-2d983026-6d7f-4805-8ad5-a9319f02a28c.png">

**Comment by gabzon** [comment]
je ne comprends pas ce que je dois faire.

**Comment by sb-fred** [comment]
Quand je clique Add Payment sur le premier écran: le 2ème écran devrait afficher par défaut dans Type: Credit (in)
Par contre, quand je clique Add Refund sur le 1er écran, le 2ème écran devrait afficher par défaut dans Type: Debit (out)

Mais en vrai, je ne vois même plus ou j'avais cette option Add Refund. Je suis passé par la liste des orders, le profil de l'élève etc... mais je ne vois que du add payment. Bon du coup ça m'oblige à bien choisir
