### ISSUE TITLE
Ordre des fiches de présence - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#77]
Dans la feuille de cours, les dates de présence sont crées en fonction de leur création et non de l'ordre chronologique. Il faudrait créer à partir de l'ordre chronologique du plus vieux à gauche au plus récent à droite

<img width="1010" alt="Screenshot 2021-09-09 at 11 10 31" src="https://user-images.githubusercontent.com/212969/132657764-aa8ceb23-4a5c-4a48-b984-bc67380c7a85.png">

**Comment by gabzon** [comment]
C'est l'admin qui crée les presences et qui ajoute la date souhaitée, donc elle peux choisi l'ordre qu'il/elle veut. 
Si on decide de faire un trie par date c'est un "enhancement" qui a mon avis on n'a pas besoin.
