### ISSUE TITLE
Erreur sur l'horaire quand j'essaie de créer un cours - Priorité 3

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#80]
Je tente de créer un cours 
> impossible d'enregistrer un horaire sur le lundi (je n'arrive pas à renseigner le format demandé en rajoutant les secondes), et donc de créer le cours complètement.
> IL SEMBLERAIT QUE CE SOIT UNIQUEMENT SUR LE LUNDI CAR JARRIVE A LE FAIRE SUR LES AUTRES JOURS (dailleurs, sur les autres jours, il est indiqué un format spécifique alors que juste hh:mm suffit)

<img width="756" alt="Capture d’écran 2021-09-09 à 12 16 18" src="https://user-images.githubusercontent.com/212969/132668213-9db9aaaa-5ad4-42b9-a6fa-a29d450c8e41.png">

**Comment by gabzon** [comment]
Tu as essaye 09:00:00?
