### ISSUE TITLE
Erreur sur le calcul automatique des frais lorsque credit card est sélectionné

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#81]
Lorsque le User sélectionne "Credit card" comme moyen de paiement, je ne comprends pas totalement la formule appliquée; car si on la suit bien (i.e. 2,8% + 0,30), je ne retombe pas sur le total de frais indiqué.

Exemple: Dans mon cas de figure, le total avec discount multi-cours et discount étudiant fait 274CHF, et 274x2,8%+0,30cts= 7,972CHF > le prix calculé quand on clique sur Credit Card ressort à 9CHF.

<img width="1242" alt="Capture d’écran 2021-09-09 à 12 35 05" src="https://user-images.githubusercontent.com/212969/132670964-b2d276e0-2580-46c8-88a8-a88d23dd5912.png">

Est-ce que le calcul arrondit? Mais attention à l'arrondi trop supérieur.

**Comment by gabzon** [comment]
Oui j'applique un arrondi.

Je crois que cela arrive car je suis en train de tout arrondir Discount + commission + total.

Je crois que c'est un problème d'ordre de la formule. J'utilise cette formule: 
(320+0.30) x 2.8% = 8.9 

Tu utilise:
(274+0.30) x 2.8% = 7.6

Je change?

**Comment by gabzon** [comment]
A changer = 274x2.8% + 0.30
