### ISSUE TITLE
Champ "Adjustment" dans Admin > Edit order sur un User

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#83]
J'essaie d'accorder un crédit à un Eleve > impossible de mettre le signe " - " dans le champ "Adjustment" car il y a un 0 qui apparaît de force, et ne part plus ensuite

<img width="822" alt="Capture d’écran 2021-09-09 à 13 03 30" src="https://user-images.githubusercontent.com/212969/132674693-f1ad4beb-5d6c-4ec5-94ec-c369ab66a5d2.png">

**Comment by gabzon** [comment]
Il suffit de mettre le curseur a gauche du zero afin de mettre le négatif ou changer le chiffre. 

C'est un problème tout con, mais j'arrive pas a l'enlever facilement, ce qui se passe, si on met rien. le system bug car il attends un chiffre, des qu'il reçoit rien il bug. C'est pour ca que je force le 0.

A revoir après
