### ISSUE TITLE
Amélioration : Sur page Users - Afficher la balance de l'élève - Priorité 0

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#84]
La aussi, Si c'est simple, c'est un truc qui nous aide beaucoup pour savoir les élèves à contacter en priorité en un coup d'oeil pour les paiements.

Ce serait sur la page Users de remplacer la colonne country/age par Balance et de pouvoir cliquer dessus pour trier par ordre de balance croissante ou décroissante. Sinon les autres data donnant le mail et le numéro de tel direct sont top pour la partie contact.

<img width="981" alt="Screenshot 2021-09-09 at 15 30 43" src="https://user-images.githubusercontent.com/212969/132695019-61095650-377f-4694-b943-2c2469b22391.png">

**Comment by gabzon** [comment]
J'ai pas encore développé le trie ici et je pourrais aussi rajouter la balance, mais il me faut plus de code, je vais ajouter cette option en "enhancement" car mnt je me focalise sur les ameliorations
