### ISSUE TITLE
Create course > vidéo qui apparaît tout le temps - PRIORITE 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#85]
Quand je crée un cours, il y a tjrs sur la page du cours une vidéo qui apparaît 
alors que je n'ai défini aucun lien de vidéo dans la section Video Information

vidéo en question:
<img width="1164" alt="Capture d’écran 2021-09-09 à 15 31 36" src="https://user-images.githubusercontent.com/212969/132695178-0a9ee6d3-9ec7-4822-a40a-b52d231e69b7.png">

> pourquoi y a-t-il une vidéo?
> comment est-elle choisi si aucun lien n'est défini?

**Comment by gabzon** [comment]
Cette video est un fault back au cas ou vous mettez pas de video. 
Est-ce que j'enlève cette video de sécurité ?
