### ISSUE TITLE
Problème Discount Promocode - Priorité 0

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#87]
J'ajoute une promotion pour un cours et une date de fin. Je n'a pas de calendrier pour choisir la date de fin, je rentre du coup en format : 15/09/2021 et j'ai un message d'erreur

<img width="1052" alt="Screenshot 2021-09-09 at 15 38 31" src="https://user-images.githubusercontent.com/212969/132696287-6c772f3e-5b3c-4721-9c8b-e867a08e47bc.png">

<img width="1074" alt="Screenshot 2021-09-09 at 15 38 51" src="https://user-images.githubusercontent.com/212969/132696318-ac6dd28c-a808-49b4-82df-1357ed8d59e5.png">

Ce serait bien d'avoir le calendrier ou le format en fond de cellule "DD/MM/YYYY" par exemple pour ne pas se tromper

**Comment by gabzon** [comment]
Il n'y a pas de code derriere, j'avais fait ca en pensent au futur pour faire les promo
Je viens de cacher cette partie
