### ISSUE TITLE
Incohérence quand je supprime une Location pour un cours donné

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#88]
Je supprime la location "Dance Area"
dans la liste de cours, rien ne change

lorsque je supprime la classroom qui était associée à "Dance Area", là seulement la classroom disparaît bien du cours

<img width="251" alt="Capture d’écran 2021-09-09 à 16 23 07" src="https://user-images.githubusercontent.com/212969/132703870-413c7d82-8e5f-435f-9ea4-b9642fddc9e7.png">

logique à revoir:
une location est nécessaire pour créer une classroom, par contre, une classroom peut exister sans location ensuite
> les 2 devraient être liés, ou alors il faut partir sur une logique où la classroom n'a pas besoin de location pour être créée

**Comment by gabzon** [comment]
La logique actuelle, si tu efface la location le system devrait effacer les salles de cours, (c'est comme ca sur mon ordi, je viens de tester) 

- Cours est associé a une classroom
- Classroom est associé a une location
- Cours et Location ne sont pas du tout associe entre eux!

Cours -> Classroom -> Location
