### ISSUE TITLE
Add order en temps qu'admin pour un élève - Priorité 0

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#89]
Sur ma liste de user, quand je clique sur l'icone pour add un order à côté d'un élève
le + dans les menus à droite

<img width="1236" alt="Screenshot 2021-09-09 at 16 16 55" src="https://user-images.githubusercontent.com/212969/132702749-598ef45c-d099-4594-959b-41b5874d8041.png">

J'arrive sur la page de création d'order, mais j'ai perdu le nom du user et dois le récupérer.

<img width="1233" alt="Screenshot 2021-09-09 at 16 17 20" src="https://user-images.githubusercontent.com/212969/132702835-48dc1225-0534-4c3b-8e08-2141c2436ecd.png">

Je ne me souviens plus si on n'arrivait plus à faire l'order directement pour l'élève concerné ou bien si c'est faisable pour éviter de devoir le choisir à nouveau.

**Comment by gabzon** [comment]
Avant c'était automatique, mnt vu que j'ai mis cette bar de recherche je n'arrive plus a l'intégrer automatiquement. 
Je vais continuer a travailler sur les autres bugs qui sont plus important et mettre cet issue en "enhancement"
