### ISSUE TITLE
Ajout d'une 2e video de teaser quand je crée un cours - Priorité 1

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#90]
je crée un cours, j'ajoute une 1ère vidéo, pas de pb
j'ajoute une 2nde vidéo, et la 1ère vidéo/1er lien disparaît, et voici ce qui s'affiche sur la page du cours 

<img width="1183" alt="Capture d’écran 2021-09-09 à 17 04 01" src="https://user-images.githubusercontent.com/212969/132711509-3ae2e6eb-d3bf-4845-ad83-c4725cd2d481.png">
<img width="1293" alt="Capture d’écran 2021-09-09 à 17 04 14" src="https://user-images.githubusercontent.com/212969/132711547-10e8e039-bc01-4ec1-b47d-e12d004db2f7.png">

**Comment by gabzon** [comment]
Je n'arrive pas a recréer ce bug. Tu peux me décrire un peu plus, quelle navigateur?
sur mon écran ca s'affiche correctement

J'ai effacé les embed et j'ai recréé ca a marché. 

Ce video je l'ai mis par défaut au cas ou vous ne mettez pas de video
