### ISSUE TITLE
Problème de suppression de cours pour élève - bouton Cancel - Priorité 2

### ISSUE THREAD

**Issue by sb-fred** [dancefloor/dms-2#91]
J'ai un élève qui fait 2 cours House et Pilate

<img width="1252" alt="Screenshot 2021-09-27 at 16 01 23" src="https://user-images.githubusercontent.com/212969/134923684-43c72ed7-84d0-4a8f-8ada-88c4f6873451.png">

Je supprime House

<img width="1270" alt="Screenshot 2021-09-27 at 16 02 06" src="https://user-images.githubusercontent.com/212969/134923803-d1bf04e3-1694-4c91-9fb6-55ca6ef3b7b2.png">

Finalement, je veux annuler mon annulation et clique sur Cancel en haut à droite.
Je reviens alors à la page des orders, mais le cours de house a disparu 

<img width="1017" alt="Screenshot 2021-09-27 at 16 02 44" src="https://user-images.githubusercontent.com/212969/134923902-0f6548fa-c1e8-4d88-b09b-9d014c94580a.png">

et par contre le montant que l'élève doit payer ne prend pas en compte la suppression (tu vois le 350 au dessus au lieu du 90 du si il n'y a qu'un cours).

<img width="965" alt="Screenshot 2021-09-27 at 16 03 56" src="https://user-images.githubusercontent.com/212969/134924113-cbd9dbb5-5a00-45f1-b1a4-318c7583f54c.png">

**Comment by gabzon** [comment]
Enlever le bouton cancel

**Comment by gabzon** [comment]
J'ai enleve le bouton cancel, mnt je viens de remarquer le problème va continuer dans le cas ou la personne click back sur le navigateur. 

Le problème arrive car j'utilise ajax une technologie qui me a jour les cours pour un order dans la bdd sans recharger la page, cela dit elle me pas a jour les différents montants ou prix, pour cela il faut clicker sur sauvegarder. 

Le system marcher, mais il faut que l'admin click sur "save". Je vais fermer mnt cette issue. 

On pourra le réouvrir après si vous voulez faire une amelioration.
